project:
  id: oc-p2
  name: oc p2
methodology: scrum
repositories:
- id: backend
  name: backend
  path: repos/backend
  url: https://github.com/jlbokass/OCP2-Back-end-java.git
- id: frontend
  name: frontend
  path: repos/frontend
  url: https://github.com/jlbokass/OCP2-Front-end-angular.git
